### ISSUE TITLE
Point to flathub.org instead of sdk.gnome.org in the flatpakref

### ISSUE THREAD

**Issue by jurf** [FragmentsApp/Fragments#1]
More people have Flathub added than sdk.gnome.org and the runtimes are basically migrated there, so there isn’t point not to use it. I’d make a PR but I can’t find it on GitHub.

The Flathub repo URL is: https://dl.flathub.org/repo/flathub.flatpakrepo

**Comment by byteturtle** [comment]
Fixed that one, and pushed the flatpakref used for the nightly builds to github: https://github.com/byteturtle/flatpakrefs

**Comment by jurf** [comment]
Thanks!
