### ISSUE TITLE
Flatpak installation does not work on my machine.

### ISSUE THREAD

**Issue by cjdm** [FragmentsApp/Fragments#4]
![fragments](https://user-images.githubusercontent.com/29413765/35835032-ccc2c81e-0aae-11e8-972b-c6f8c2d6fef6.png)

**Comment by byteturtle** [comment]
Please check if you can visit https://repos.byteturtle.eu/ in your browser, if that works please try again.

**Comment by cjdm** [comment]
![fragments](https://user-images.githubusercontent.com/29413765/35871939-e74a21cc-0b3b-11e8-8ea5-f72c4cc86f0e.png)
It works in my browser, but I cannot install all the same.

**Comment by haecker-felix** [comment]
Try it with following command:

`flatpak install --from https://repos.byteturtle.eu/fragments-master.flatpakref --verbose`

Please post the complete output.

**Comment by byteturtle** [comment]
I can't reproduce this error on my side with Flatpak 0.10.3 on Arch. To me it looks like a general DNS issue on your end. Check that you are on a current Flatpak version and maybe open an issue over at the flatpak repo: https://github.com/flatpak/flatpak/issues/new
