### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Fabioah** [FragmentsApp/Fragments#5]
Hi, is there any way to build this app without flatpak?
My pc is quite old and if it's possible I would prefer install just Fragments.

**Comment by haecker-felix** [comment]
Well, there is a Arch AUR package available.

But the age of your PC shouldn't be a problem to use flatpak.

Unfortunately there aren't other possibilities right now to install fragments.

**Comment by Fabioah** [comment]
Ok, thank you.
